name: Lint Code
on: [push]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a
          # proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: false  # do not check SLURM files
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_FLAKE8: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
