name: Lint Code
on: [push]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a
          # proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code
        uses: github/super-linter@v4
        env:
          # lint all files (we can disable it later to lint only new and updated files)
          # https://github.com/github/super-linter/wiki#only-linting-new-files
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_FLAKE8: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
